"""Generate a standalone Playwright script from a completed aiwebtest report."""

from __future__ import annotations

import json
from typing import Any

from ..agent.schemas import StepKind, TestReport

_SNAPSHOT_JS = r"""
() => {
  const REF_ATTR = 'data-aiwebtest-ref';
  const INTERACTIVE = new Set(['A', 'BUTTON', 'INPUT', 'SELECT', 'TEXTAREA']);
  const elements = [];
  let counter = 0;

  const isVisible = (el) => {
    const style = window.getComputedStyle(el);
    if (style.display === 'none' || style.visibility === 'hidden' || style.opacity === '0') {
      return false;
    }
    const rect = el.getBoundingClientRect();
    return rect.width > 0 && rect.height > 0;
  };

  const accessibleName = (el) => {
    const aria = el.getAttribute('aria-label');
    if (aria) return aria.trim();
    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.tagName === 'SELECT') {
      if (el.labels && el.labels.length) return el.labels[0].textContent.trim();
      const ph = el.getAttribute('placeholder');
      if (ph) return ph.trim();
      const name = el.getAttribute('name');
      if (name) return name.trim();
    }
    const text = (el.innerText || el.textContent || '').trim().replace(/\s+/g, ' ');
    return text.slice(0, 120);
  };

  const role = (el) => {
    const explicit = el.getAttribute('role');
    if (explicit) return explicit;
    const tag = el.tagName;
    if (tag === 'A') return 'link';
    if (tag === 'BUTTON') return 'button';
    if (tag === 'SELECT') return 'select';
    if (tag === 'TEXTAREA') return 'textbox';
    if (tag === 'INPUT') return (el.getAttribute('type') || 'text');
    if (/^H[1-6]$/.test(tag)) return 'heading';
    return tag.toLowerCase();
  };

  const candidates = document.querySelectorAll(
    'a, button, input, select, textarea, [role="button"], [role="link"], [onclick], ' +
    'h1, h2, h3, label, [data-testid]'
  );

  for (const el of candidates) {
    if (!isVisible(el)) continue;
    const name = accessibleName(el);
    const interactive = INTERACTIVE.has(el.tagName) ||
      el.hasAttribute('onclick') || ['button', 'link'].includes(el.getAttribute('role'));
    if (!name && !interactive) continue;
    const ref = 'e' + (++counter);
    el.setAttribute(REF_ATTR, ref);
    elements.push({
      ref,
      tag: el.tagName.toLowerCase(),
      role: role(el),
      name,
      value: (el.value !== undefined ? String(el.value) : '').slice(0, 80),
    });
  }
  return elements;
}
"""


def generate_playwright_script(report: TestReport) -> str:
    """Return Python code that replays the recorded browser tool calls."""
    lines = [
        '"""Generated by aiwebtest. Replays one completed run without an AI model."""',
        "",
        "from __future__ import annotations",
        "",
        "import asyncio",
        "import os",
        "import time",
        "from pathlib import Path",
        "",
        "from playwright.async_api import async_playwright",
        "",
        f"SNAPSHOT_JS = {json.dumps(_SNAPSHOT_JS)}",
        "",
        "",
        "async def snapshot(page):",
        "    elements = await page.evaluate(SNAPSHOT_JS)",
        "    print(f'Snapshot: {len(elements)} elements at {page.url}')",
        "    for el in elements:",
        "        name = f\" {el['name']!r}\" if el.get('name') else ''",
        "        print(f\"  [ref={el['ref']}] {el['role']}{name}\")",
        "    return elements",
        "",
        "",
        "def by_ref(page, ref):",
        "    return page.locator(f'[data-aiwebtest-ref=\"{ref}\"]')",
        "",
        "",
        "async def tag(page, expected_ref=None, timeout_ms=10000):",
        "    # Re-apply ref attributes to the live DOM. The ref ids are assigned by",
        "    # SNAPSHOT_JS and wiped whenever the page re-renders or navigates, so we",
        "    # refresh them right before each ref-based action to keep replay reliable.",
        "    deadline = time.monotonic() + timeout_ms / 1000",
        "    last_count = 0",
        "    while True:",
        "        elements = await page.evaluate(SNAPSHOT_JS)",
        "        last_count = len(elements)",
        "        if expected_ref is None or any(el.get('ref') == expected_ref for el in elements):",
        "            return elements",
        "        if time.monotonic() >= deadline:",
        "            raise TimeoutError(",
        "                f'Ref {expected_ref!r} did not appear after {timeout_ms}ms '",
        "                f'({last_count} refs on {page.url})'",
        "            )",
        "        try:",
        "            await page.wait_for_load_state('domcontentloaded', timeout=500)",
        "        except Exception:",
        "            pass",
        "        await page.wait_for_timeout(100)",
        "",
        "",
        "async def settle(page):",
        "    try:",
        "        await page.wait_for_load_state('domcontentloaded', timeout=1000)",
        "    except Exception:",
        "        pass",
        "    await page.wait_for_timeout(100)",
        "",
        "",
        "async def assert_that(page, condition, ref=None, expected=None, description=''):",
        "    await tag(page, ref)",
        "    if condition == 'visible':",
        "        if not ref:",
        "            raise AssertionError(f'{description}: no ref provided')",
        "        actual = await by_ref(page, ref).is_visible()",
        "        if not actual:",
        "            raise AssertionError(f'{description}: expected visible')",
        "    elif condition == 'url_contains':",
        "        if (expected or '') not in page.url:",
        "            raise AssertionError(f'{description}: {expected!r} not in {page.url!r}')",
        "    elif condition == 'text_contains':",
        "        if ref:",
        "            actual = await by_ref(page, ref).inner_text()",
        "        else:",
        "            actual = await page.inner_text('body')",
        "        if (expected or '') not in actual:",
        "            preview = actual[:500]",
        "            raise AssertionError(f'{description}: {expected!r} not found in {preview!r}')",
        "    elif condition == 'value_equals':",
        "        if not ref:",
        "            raise AssertionError(f'{description}: no ref provided')",
        "        actual = await by_ref(page, ref).input_value()",
        "        if actual != (expected or ''):",
        "            raise AssertionError(f'{description}: expected {expected!r}, got {actual!r}')",
        "    else:",
        "        raise AssertionError(f'{description}: unknown condition {condition!r}')",
        "    print(f'PASS: {description or condition}')",
        "",
        "",
        "async def main():",
        "    async with async_playwright() as pw:",
        "        # Headful by default; set AIWEBTEST_REPLAY_HEADLESS=1 to run headless.",
        "        headless = os.environ.get('AIWEBTEST_REPLAY_HEADLESS', '') == '1'",
        "        browser = await pw.chromium.launch(headless=headless)",
        "        context = await browser.new_context(viewport={'width': 1280, 'height': 800})",
        "        page = await context.new_page()",
        "        screenshots_dir = Path('generated_screenshots')",
        "        screenshots_dir.mkdir(exist_ok=True)",
        "        try:",
    ]

    body = _render_steps(report)
    if body:
        lines.extend("            " + line if line else "" for line in body)
    else:
        lines.append("            print('No replayable tool calls were recorded.')")

    lines.extend(
        [
            "        finally:",
            "            await context.close()",
            "            await browser.close()",
            "",
            "",
            "if __name__ == '__main__':",
            "    asyncio.run(main())",
            "",
        ]
    )
    return "\n".join(lines)


def _render_steps(report: TestReport) -> list[str]:
    lines: list[str] = []
    shot_index = 0
    for step in report.steps:
        if step.kind != StepKind.TOOL_CALL or not step.tool_name:
            continue
        args = step.tool_input or {}
        tool = step.tool_name
        lines.append(f"print('tool: {tool}')")
        # Refresh ref attributes on the current DOM before any ref-based action.
        # assert_that refreshes them itself, so skip the duplicate there.
        if args.get("ref") and tool != "assert_that":
            lines.append(f"await tag(page, {_py(args.get('ref'))})")
        if tool == "navigate":
            url = _py(args.get("url", ""))
            lines.append(f"await page.goto({url}, wait_until='load')")
        elif tool == "get_page_snapshot":
            lines.append("await snapshot(page)")
        elif tool == "click":
            lines.append(f"await by_ref(page, {_py(args.get('ref', ''))}).click()")
            lines.append("await settle(page)")
        elif tool == "type_text":
            ref = _py(args.get("ref", ""))
            text = _py(args.get("text", ""))
            lines.append(f"await by_ref(page, {ref}).fill({text})")
            if args.get("submit"):
                lines.append(f"await by_ref(page, {ref}).press('Enter')")
                lines.append("await settle(page)")
        elif tool == "select_option":
            lines.extend(_select_option_lines(args))
            lines.append("await settle(page)")
        elif tool == "press_key":
            lines.append(f"await page.keyboard.press({_py(args.get('key', ''))})")
            lines.append("await settle(page)")
        elif tool == "wait_for":
            lines.extend(_wait_for_lines(args))
        elif tool == "screenshot":
            shot_index += 1
            lines.append(
                "await page.screenshot("
                f"path=str(screenshots_dir / 'shot_{shot_index:03d}.png'), "
                f"full_page={bool(args.get('full_page', False))})"
            )
        elif tool == "get_text":
            if args.get("ref"):
                lines.append(f"print(await by_ref(page, {_py(args.get('ref'))}).inner_text())")
            else:
                lines.append("print(await page.inner_text('body'))")
        elif tool == "assert_that":
            lines.append(
                "await assert_that(page, "
                f"condition={_py(args.get('condition', ''))}, "
                f"ref={_py(args.get('ref'))}, "
                f"expected={_py(args.get('expected'))}, "
                f"description={_py(args.get('description', ''))})"
            )
        elif tool == "finish_test":
            lines.append(f"print({_py('Finished: ' + str(args.get('summary', '')))})")
        else:
            lines.append(f"print('Skipped unsupported tool: {tool}')")
    return lines


def _select_option_lines(args: dict[str, Any]) -> list[str]:
    ref = _py(args.get("ref", ""))
    value = _py(args.get("value", ""))
    return [
        "try:",
        f"    await by_ref(page, {ref}).select_option(value={value})",
        "except Exception:",
        f"    await by_ref(page, {ref}).select_option(label={value})",
    ]


def _wait_for_lines(args: dict[str, Any]) -> list[str]:
    state = args.get("state")
    timeout = int(args.get("timeout_ms", 10000))
    if state in {"visible", "hidden"}:
        return [
            f"await by_ref(page, {_py(args.get('ref', ''))}).wait_for("
            f"state={_py(state)}, timeout={timeout})"
        ]
    return [
        f"await page.get_by_text({_py(args.get('value', ''))}).first.wait_for(timeout={timeout})"
    ]


def _py(value: Any) -> str:
    return repr(value)
